/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  // stuff I placed into sidebars.js





  productsSidebar: [
    {
      type: 'doc',
      id: 'builder/overview',
      label: 'Overview',
      className: 'overview-styling',
    },
    {
      type: 'category',
      label: 'Wallets',
      items: ['builder-wallet/overview', 'builder-wallet/customize-wallet', 'builder-wallet/create-vault'],
      collapsed: true,
      className: 'wallet-styling',
    },
    {
      type: 'category',
      label: 'Marketplace',
      items: ['builder-marketplaces/overview', 'builder-marketplaces/customize-marketplace', 'builder-marketplaces/create-embedded-marketplace'],
      collapsed: true,
      className: 'marketplace-styling',
    },
    {
      type: 'category',
      label: 'Items and Collectibles',
      items: ['builder-minter/overview', 'builder-minter/mint-collectibles', 'builder-minter/get-balance', 'builder-minter/mint-items', 'builder-minter/update-metadata', 'builder-minter/send-rewards'],
      collapsed: true,
      className: 'minter-styling',
    },
    {
      type: 'category',
      label: 'Payments',
      items: ['builder-payments/overview', 'builder-payments/nft-purchase'],
      collapsed: true,
      className: 'payment-styling',
    },
    {
      type: 'link',
      label: 'Authentication',
      href: '/',
      className: 'auth-styling',
    },
    {
      type: 'link',
      label: 'Node Provider',
      href: '/',
      className: 'node-styling',
    },
    {
      type: 'link',
      label: 'Indexer',
      href: '/',
      className: 'indexer-styling',
    },
    {
      type: 'link',
      label: 'Transaction Relayer',
      href: '/',
      className: 'payment-styling',
    },
  ],

  apisdksSidebar: [
    {
      type: 'category',
      label: 'Wallet SDKs',
      items: ['integration-wallet-sdks/unity-sdk', 'integration-wallet-sdks/unreal-sdk', 'integration-wallet-sdks/web-sdk'],
      collapsed: true,
      className: 'wallet-styling',
    },
    {
      type: 'doc',
      label: 'Marketplace API',
      id: 'integration-marketplace-api/overview',
      className: 'marketplace-styling',
    },
    {
      type: 'category',
      label: 'Minter API',
      items: ['integration-minter/mint-collectibles', 'integration-minter/get-balance', 'integration-minter/mint-items', 'integration-minter/update-metadata', 'integration-minter/send-rewards'],
      collapsed: true,
      className: 'minter-styling',
    },
    {
      type: 'link',
      label: 'Authenticaion',
      href: '/',
      className: 'auth-styling',
    },
    {
      type: 'link',
      label: 'Node Gateway API',
      href: '/',
      className: 'node-styling',
    },
    {
      type: 'link',
      label: 'Indexer API',
      href: '/',
      className: 'indexer-styling',
    },
    {
      type: 'link',
      label: 'Transaction API',
      href: '/',
      className: 'payment-styling',
    },
  ]





/*

  productsSidebar: [
    {
      type: 'doc',
      id: 'builder/overview',
      label: 'Overview',
      className: 'overview-styling-bw',
    },
    {
      type: 'category',
      label: 'Wallets',
      items: ['builder-wallet/overview', 'builder-wallet/customize-wallet', 'builder-wallet/create-vault'],
      collapsed: true,
      className: 'wallet-styling-bw',
    },
    {
      type: 'category',
      label: 'Marketplace',
      items: ['builder-marketplaces/overview', 'builder-marketplaces/customize-marketplace', 'builder-marketplaces/create-embedded-marketplace'],
      collapsed: true,
      className: 'marketplace-styling-bw',
    },
    {
      type: 'category',
      label: 'Items and Collectibles',
      items: ['builder-minter/overview', 'builder-minter/mint-collectibles', 'builder-minter/get-balance', 'builder-minter/mint-items', 'builder-minter/update-metadata', 'builder-minter/send-rewards'],
      collapsed: true,
      className: 'minter-styling-bw',
    },
    {
      type: 'category',
      label: 'Payments',
      items: ['builder-payments/overview', 'builder-payments/nft-purchase'],
      collapsed: true,
      className: 'payment-styling-bw',
    },
    {
      type: 'link',
      label: 'Authentication',
      href: '/',
      className: 'auth-styling-bw',
    },
    {
      type: 'link',
      label: 'Node Provider',
      href: '/',
      className: 'node-styling-bw',
    },
    {
      type: 'link',
      label: 'Indexer',
      href: '/',
      className: 'indexer-styling-bw',
    },
    {
      type: 'link',
      label: 'Transaction API',
      href: '/',
      className: 'payment-styling-bw',
    },
  ],

  apisdksSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/quickstart', 'getting-started/get-access-key-in-builder'],
      collapsed: false,
    },
  ]


*/




  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
