name: Build Documentation and Push to Build

on:
  push:
   branches:
    - master

jobs:
  build:
   runs-on: ubuntu-latest
   name: Build and Push
   steps:
    - name: git-checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install
    
    - name: Build
      run: pnpm build

    - name: Touch CNAME
      run: echo "docs.sequence.xyz" > build/CNAME
      
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
